### ISSUE TITLE
Platform error

### ISSUE THREAD

**Issue by tpzltn** [MortJC/homebridge-platform-isolarcloud#3]
Hi,

Atfer I configure the HB and restart I got this error:

Error: The requested platform 'isolarcloud' was not registered by any plugin.

Any ideas for the fix?

Thanks.

**Comment by tpzltn** [comment]
Fixed:

config.json is case sensitive so you should use:
"platform": "ISolarCloud"

But still got an error:
[6/23/2021, 2:46:10 PM] [isolarcloud] TypeError: Cannot read property 'pageList' of null
    at ISolarCloudAPI.getPowerStations (/usr/local/lib/node_modules/homebridge-platform-isolarcloud/isolarcloudapi.js:51:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:9713) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at PlatformISolarCloud.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-isolarcloud/platform.js:51:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by MortJC** [comment]
Thanks for the correct of the name case.

Can you please enable debugging and send the logs?

**Comment by palla89** [comment]
hi! i have the same problem, do someone have a fix?

```
[4/15/2023, 8:30:39 PM] [ISolarCloud] TypeError: Cannot read properties of null (reading 'pageList')
    at ISolarCloudAPI.<anonymous> (/homebridge/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:77:37)
    at step (/homebridge/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
    at Object.next (/homebridge/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
    at fulfilled (/homebridge/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/15/2023, 8:30:39 PM] TypeError: Cannot read properties of null (reading 'pageList')
    at ISolarCloudAPI.<anonymous> (/homebridge/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:77:37)
    at step (/homebridge/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
    at Object.next (/homebridge/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
    at fulfilled (/homebridge/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
