### ISSUE TITLE
Plugin doesnt seem to read info, shows 0 LUX

### ISSUE THREAD

**Issue by Nach0-Stallion** [MortJC/homebridge-platform-isolarcloud#6]
I had this plugin working wonderfully without issue for ages, recently i went to check via homekit and it shows 0 lux, going into the logs seems to have errors.
I know the app/website has recently changed so i don't know if the API has changed?
here is from the logs:
on start up it says its a remembered accessory and configuring handlers, maybe i need to clear it all first?
`[1/2/2022, 1:29:51 PM] [ISolarCloud] Remembered accessory, configuring handlers BXXXXXXX MyUsername`

`[1/2/2022, 1:29:53 PM] [ISolarCloud] TypeError: Cannot read property 'pageList' of null
at ISolarCloudAPI.<anonymous> (/usr/lib/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:62:37)
at step (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
at Object.next (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
at fulfilled (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:394) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageList' of null
at ISolarCloudAPI.<anonymous> (/usr/lib/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:62:37)
at step (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
at Object.next (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
at fulfilled (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:394) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. `

Any help is greatly appreciated, 
Thank you and have a wonderful new year/

**Comment by MortJC** [comment]
Hi. Looks like isolarcloud have separated different regions to different servers. I've updated the plugin to include a server parameter. Just set it to the same server name you use on the app. E.g. Australian

**Comment by Nach0-Stallion** [comment]
oh that's awesome, thank you so much! (all up and running now!!!)
