### ISSUE TITLE
iSolarCloud crashing HomeBridge

### ISSUE THREAD

**Issue by x5nder** [MortJC/homebridge-platform-isolarcloud#8]
Since yesterday, the iSolarCloud plugin is crashing my HomeBridge installation with this error log:

[11/30/2023, 11:19:44 PM] TypeError: Cannot read properties of null (reading 'pageList')
    at ISolarCloudAPI.<anonymous> (/usr/lib/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:77:37)
    at step (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
    at Object.next (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
    at fulfilled (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Any idea what's going on? Did iSolarCloud change anything on their end to break the plugin?

**Comment by Nach0-Stallion** [comment]
** EDIT**
Looks like other people on Homeassistant having issues with API errors, so i think sungrow/isolarcloud have changed or disabled their API's
******

I just updated my Unraid server and noticed that the isolar plugin was removed from homebridge, when i re-added it i noted it read the accessory info for my plant, but had since just kept bombing out.
suspecting homebridge has updated something that the plugin doesnt like?

Love the plugin, hope its something that can be resolved! Cheers
This is my error log:
Seems a lot of it is identical
`[12/3/2023, 4:00:55 AM] [ISolarCloud] TypeError: Cannot read properties of null (reading 'token')
    at ISolarCloudAPI.<anonymous> (/usr/lib/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:50:46)
    at step (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
    at Object.next (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
    at fulfilled (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/3/2023, 4:00:55 AM] [ISolarCloud] TypeError: Cannot read properties of null (reading 'pageList')
    at ISolarCloudAPI.<anonymous> (/usr/lib/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:77:37)
    at step (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
    at Object.next (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
    at fulfilled (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/3/2023, 4:00:55 AM] TypeError: Cannot read properties of null (reading 'pageList')
    at ISolarCloudAPI.<anonymous> (/usr/lib/node_modules/homebridge-platform-isolarcloud/src/isolarcloudapi.ts:77:37)
    at step (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:33:23)
    at Object.next (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:14:53)
    at fulfilled (/usr/lib/node_modules/homebridge-platform-isolarcloud/dist/isolarcloudapi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/3/2023, 4:00:55 AM] Got SIGTERM, shutting down Homebridge...`

**Comment by MortJC** [comment]
Looks like they have changed the API. Although I can find the new appkey, they are now encrpting the request payloads. 

Sorry, but it's going to take a while to work this out...

**Comment by Nach0-Stallion** [comment]
Thank you for looking into it, appreciate your efforts!

**Comment by Churro-blaze** [comment]
Thanks for looking into it. 
Love the plugin. It's used in a few automations

**Comment by x5nder** [comment]
Yeah, thanks in advance... same here, used in automations!

**Comment by poppin-fresh** [comment]
Same issue here. Many thanks @MortJC for the plugin and for looking into it!

**Comment by Nach0-Stallion** [comment]
Hello @MortJC 
I was looking around for updates and someone posted this about sungrow:
[link](https://gist.github.com/Paraphraser/cad3b0aa6428c58ee87bc835ac12ed37)

Not sure if this is related or helps you at all but thought I'd mention it, happy new year!

**Comment by KedsSparrsh04** [comment]
Is it working now?

**Comment by richardmarr** [comment]
Are you thinking you will update this @MortJC ? thanks!

**Comment by MortJC** [comment]
New v1.3.0 release which handles the new encryption

**Comment by Churro-blaze** [comment]
Thank you very much.

**Comment by MortJC** [comment]
No problem.

I'm interested to know if you are using it for any automation?

**Comment by Churro-blaze** [comment]
Yeah I do.  For two things. Using Homebridge. 
When the solar gets above 3000w it turns on the spa and sets a rule to stay on until midnight so on a cloudy day the spa doesn’t get heated but that’s ok, saves a lot of power. 
And secondly 2 hours before sunset if the lux drops below a level it turns on the garden lights, early for overcast evenings. 
would love to know who else using it and for why.

**Comment by richardmarr** [comment]
I will let you know… yet to install it…. But I like the idea of turning on my pool heater based upon power generated etc
